version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        env_file:
            - .env

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        volumes:
            - db_data:/var/lib/mysql
        env_file:
            - .env
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel_phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"

volumes:
    db_data:
        driver: local
