version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        env_file:
            - .env

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        container_name: laravel_mysql
        volumes:
            - db_data:/var/lib/mysql
        env_file:
            - .env
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel_phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"

volumes:
    db_data:
        driver: local
